version: 2
jobs:
    # Latest build
    build:
        machine: true
        steps:
            - checkout
            - run: ./build.sh 7.2
            - run: ./publish.sh 7.2

    build-5.6:
        machine: true
        steps:
            - checkout
            - run: ./build.sh 5.6
            - run: ./publish.sh 5.6

    build-7.0:
        machine: true
        steps:
            - checkout
            - run: ./build.sh 7.0
            - run: ./publish.sh 7.0

    build-7.1:
        machine: true
        steps:
            - checkout
            - run: ./build.sh 7.1
            - run: ./publish.sh 7.1

workflows:
    version: 2

    build_versions:
        jobs:
            - build:
                filters:
                    branches:
                        only:
                            - master
            - build-5.6:
                filters:
                    branches:
                        only:
                            - master

            - build-7.0:
                filters:
                    branches:
                        only:
                            - master

            - build-7.1:
                  filters:
                      branches:
                          only:
                              - master